// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKlbQTxkivs9EPTiqEZ87HbdFADvAeD1M',
    appId: '1:897468631800:web:f54ac346756440fe7dc90d',
    messagingSenderId: '897468631800',
    projectId: 'mind--app-ec238',
    authDomain: 'mind--app-ec238.firebaseapp.com',
    storageBucket: 'mind--app-ec238.appspot.com',
    measurementId: 'G-JEQV48428J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5ugHao_S_l7wz-mDQHX1QL-rx7cLBgQ',
    appId: '1:897468631800:android:0eb80a5aca81ac7e7dc90d',
    messagingSenderId: '897468631800',
    projectId: 'mind--app-ec238',
    storageBucket: 'mind--app-ec238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxqXNx0pPuhzt2MmrMgRqVkt_Vxkj2cHs',
    appId: '1:897468631800:ios:b1ac982ade679c207dc90d',
    messagingSenderId: '897468631800',
    projectId: 'mind--app-ec238',
    storageBucket: 'mind--app-ec238.appspot.com',
    iosClientId: '897468631800-tl1k4voa1i34fluksgso43lfnn9vnq6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindApp',
  );
}
